# Generated by Django 4.2.7 on 2023-12-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('CountryCode', models.CharField(max_length=30)),
                ('Population', models.IntegerField()),
            ],
            options={
                'db_table': 'base',
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=55)),
                ('status', models.CharField(max_length=30)),
                ('data_scraped', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('scraped_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
