# Generated by Django 4.2.7 on 2023-12-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='scraped_at',
            new_name='scraped_on',
        ),
    ]
