# Generated by Django 4.2.7 on 2023-12-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fema', '0002_rename_scraped_at_city_scraped_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='scraped_on',
            new_name='scraped_at',
        ),
    ]
